# Generated by Django 5.2.4 on 2025-07-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_ikigairesult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('habilidades_clave', models.TextField()),
            ],
        ),
    ]
